package com.assignment.pgrkam_app.models

data class GovtJobs(
    val id: String,
    val company_name: String,
    val govt: String,
    val job_title: String,
    val location: String,
    val description: String,
    val display_qualification: String,
    val search_qualification: String,
    val education_level: String,
    val education_level2: String,
    val search_qualification2: String,
    val specialization1: String?,
    val specialization2: String?,
    val designation: String?,
    val minmark: String,
    val district_id: String?,
    val experience: String,
    val specialization: String,
    val min_exp: String,
    val max_exp: String,
    val salary: String?,
    val gender_preference: String,
    val gender_search: String?,
    val min_age_search: String?,
    val min_age: String,
    val max_age: String,
    val vacancy: String,
    val last_date: String,
    val walk_in_interview: String,
    val posted_on: String,
    val pdf_link: String,
    val apply_link: String,
    val apply_mode: String,
    val status: String,
    val remarks: String?,
    val dbees_remarks: String,
    val dbee_reply: String,
    val created_at: String,
    val updated_at: String,
    val postedBy: String,
    val posted_dbee: String
)

